// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {models} from '../models';
import {db} from '../models';

export function ApplyUpdate():Promise<void>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function CloudFolderSuggestions():Promise<Array<main.CloudFolder>>;

export function CreateAccount(arg1:models.Account):Promise<models.Account>;

export function CreateBudget(arg1:models.Budget):Promise<models.Budget>;

export function CreateCategory(arg1:models.Category):Promise<models.Category>;

export function CreateFile():Promise<main.FileState>;

export function CreateTransaction(arg1:models.Transaction):Promise<models.Transaction>;

export function DeleteAccount(arg1:number):Promise<void>;

export function DeleteBudget(arg1:number):Promise<void>;

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteTransaction(arg1:number):Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetBudgetPage(arg1:number,arg2:number):Promise<main.BudgetPage>;

export function GetCashFlow(arg1:number,arg2:number):Promise<main.CashFlow>;

export function GetCategoryTransactionCount(arg1:number):Promise<number>;

export function GetFileState():Promise<main.FileState>;

export function GetMonthSummary(arg1:number,arg2:number):Promise<main.MonthSummary>;

export function GetNetWorthHistory(arg1:number):Promise<Array<db.NetWorthPoint>>;

export function GetTransaction(arg1:number):Promise<models.Transaction>;

export function ListAccounts():Promise<Array<models.Account>>;

export function ListBudgets():Promise<Array<models.Budget>>;

export function ListCategories():Promise<Array<models.Category>>;

export function ListTransactions(arg1:db.TxFilter):Promise<db.TxPage>;

export function MoveFile():Promise<main.FileState>;

export function OpenFile():Promise<main.FileState>;

export function PickAndImportCSV(arg1:number):Promise<main.ImportResult>;

export function PickAndImportOFX(arg1:number):Promise<main.ImportResult>;

export function ResolveDuplicate(arg1:string,arg2:number,arg3:number):Promise<void>;

export function UpdateAccount(arg1:models.Account):Promise<void>;

export function UpdateBudget(arg1:models.Budget):Promise<void>;

export function UpdateCategory(arg1:models.Category):Promise<void>;

export function UpdateTransaction(arg1:models.Transaction):Promise<void>;
