// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CloudFolderSuggestions() {
  return window['go']['main']['App']['CloudFolderSuggestions']();
}

export function CreateAccount(arg1) {
  return window['go']['main']['App']['CreateAccount'](arg1);
}

export function CreateBudget(arg1) {
  return window['go']['main']['App']['CreateBudget'](arg1);
}

export function CreateCategory(arg1) {
  return window['go']['main']['App']['CreateCategory'](arg1);
}

export function CreateFile() {
  return window['go']['main']['App']['CreateFile']();
}

export function CreateTransaction(arg1) {
  return window['go']['main']['App']['CreateTransaction'](arg1);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DeleteBudget(arg1) {
  return window['go']['main']['App']['DeleteBudget'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteTransaction(arg1) {
  return window['go']['main']['App']['DeleteTransaction'](arg1);
}

export function GetBudgetPage(arg1, arg2) {
  return window['go']['main']['App']['GetBudgetPage'](arg1, arg2);
}

export function GetCashFlow(arg1, arg2) {
  return window['go']['main']['App']['GetCashFlow'](arg1, arg2);
}

export function GetCategoryTransactionCount(arg1) {
  return window['go']['main']['App']['GetCategoryTransactionCount'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetFileState() {
  return window['go']['main']['App']['GetFileState']();
}

export function GetMonthSummary(arg1, arg2) {
  return window['go']['main']['App']['GetMonthSummary'](arg1, arg2);
}

export function GetNetWorthHistory(arg1) {
  return window['go']['main']['App']['GetNetWorthHistory'](arg1);
}

export function GetTransaction(arg1) {
  return window['go']['main']['App']['GetTransaction'](arg1);
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function ListBudgets() {
  return window['go']['main']['App']['ListBudgets']();
}

export function ListCategories() {
  return window['go']['main']['App']['ListCategories']();
}

export function ListTransactions(arg1) {
  return window['go']['main']['App']['ListTransactions'](arg1);
}

export function MoveFile() {
  return window['go']['main']['App']['MoveFile']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function PickAndImportCSV(arg1) {
  return window['go']['main']['App']['PickAndImportCSV'](arg1);
}

export function PickAndImportOFX(arg1) {
  return window['go']['main']['App']['PickAndImportOFX'](arg1);
}

export function ResolveDuplicate(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveDuplicate'](arg1, arg2, arg3);
}

export function UpdateAccount(arg1) {
  return window['go']['main']['App']['UpdateAccount'](arg1);
}

export function UpdateBudget(arg1) {
  return window['go']['main']['App']['UpdateBudget'](arg1);
}

export function UpdateCategory(arg1) {
  return window['go']['main']['App']['UpdateCategory'](arg1);
}

export function UpdateTransaction(arg1) {
  return window['go']['main']['App']['UpdateTransaction'](arg1);
}
